name: "Check Chart Version Upgrade"
description: "Action to check if a chart version upgrade was made in the PR"
inputs:
  prNumber:
    description: "The PR number to check for version upgrade"
    required: true
  repoName:
    description: "The name of the repository"
    required: true
runs:
  using: 'node20'
  image: "dist/index.mjs"
  args:
    - ${{ inputs.prNumber }}
    - ${{ inputs.githubToken }}
