name: "Check Chart Version Upgrade"
description: "Action to check if a chart version upgrade was made in the PR"
inputs:
  prNumber:
    description: "The PR number to check for version upgrade"
    required: true
  repoName:
    description: "The name of the repository"
    required: true
  ignorePaths:
    description: "Paths to ignore in the diff"
    required: false
    default: ""
runs:
  using: 'node20'
  main: "dist/index.mjs"
